accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    
	path('',views.log_in, name='login'),
	path('logout/',views.log_out, name='logout'),
	path('password/', views.change_password, name='change_password'),
]

cal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
	url(r'^checkin/$',views.checkin, name='check_in'),
	path('checkout/<int:pk>/', views.checkout, name='check_out'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
	# url(r'^Leaveview/$', views.LeaveView.as_view(), name='LeaveView'),
    url(r'^leave/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<Leave_id>\d+)/$', views.event, name='event_edit'),
	path('view_attendance/<int:pk>/', views.view_attendance, name='view_attendance'),
	path('view_leave/<int:pk>/',views.view_leave,name='view_leave'),
]
#path('edit/<int:pk>/', views.Editfiles,name='Editfiles'),

testsql/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
	#path('base/', views.base, name='layout'),
	path('', include('accounts.urls')),
	#path('',views.log_in, name='login'),
	#path('logout/',views.log_out, name='logout'),
	#path('home/', include('DMS.urls')),
	path('upload/', include('upload.urls')),
	path('cal/', include('cal.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .import views
#from django.views.generic import TemplateView
from .views import BasicUploadView, ProgressBarUploadView,DragAndDropUploadView

app_name='upload'
urlpatterns = [
	
	path('', views.file_upload,name='file_upload'),
	path('folder/', views.create_folder,name='folder'),
	path('add_file/', views.add_file, name='add_file'),
	path('<id>/remove_folder/',views.remove_folder,name='remove_folder'),
	path('<id>/rename_folder/',views.rename_folder,name='rename_folder'),
	path('<id>/folder_detail',views.folder_detail,name="folder_detail"),
	path('files/', views.upload_files,name='files'),
	path('search/', views.search_file,name='search_files'),
	path('searchfile/', views.Search_File_New,name='search_file_new'),
	path('filterfiles/', views.filterfiles,name='filterfiles'),
	#path('files/<int:pk>/', views.FileUpdateView.as_view(),name='edit_file'),
	path('edit/<int:pk>/', views.Editfiles,name='Editfiles'),
	#path('edit_save/<int:pk>/', views.Editfiles_save,name='Editfiles_save'),
	path('view/<int:pk>/', views.Viewfiles,name='Viewfiles'),
	path('Download/<int:pk>/', views.Downloadfiles,name='Downloadfiles'),
	path('signup/',views.signup,name='signup'),
	path('manage_user/',views.manage_user,name='manage_user'),
	path('users/',views.user_list_new,name='user_list_new'),
	path('modify/<int:pk>/',views.modify_user,name='modify_user'),
	path('Contacts/',views.UserContacts,name='Contacts'),
	path('addContacts/',views.ADDContacts,name='addContacts'),
	path('search_contact/',views.Search_Contact,name='Search_Cont'),
	path('clear/', views.clear_database, name='clear_database'),
    #path('', BasicFileUploadView.as_view(), name='basic-upload'),
	path('basic/', BasicUploadView.as_view(), name='basic_upload'),
	#path('multiple/', MultipleUploadView.as_view(), name='multiple_upload'),
	path('progressbar/', ProgressBarUploadView.as_view(), name='progress_bar_upload'),
	path('draganddrop/', DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
	path('multipleupload/', views.multipleupload, name='multipleupload'), 
	path('view_profile/', views.view_profile, name='view_profile'),
	#path('change_profile_image/', views.change_profile_image, name='change_profile_image'),
	path('update_profile_image/', views.update_profile_image, name='update_profile_image'),
	path('view_user_profile/<int:pk>/', views.view_user_profile, name='view_user_profile'),

	
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    def __str__(self):
        return Event.objects.filter(user=request.user)
    
class Leave(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    leave_type = models.CharField(max_length=100,null=True)
    Reason = models.TextField(null=True)
    From = models.DateField(null=True)
    To = models.DateField(null=True)
    

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Leave

class EventForm(ModelForm):
  class Meta:
    model = Leave
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'From': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
      'To': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
    }
    fields = ('leave_type','Reason','From','To')

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['From'].input_formats = ('%Y-%m-%d',)
    self.fields['To'].input_formats = ('%Y-%m-%d',)

cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from django.shortcuts import redirect
from .models import *
from .utils import Calendar
from .forms import EventForm
from django.contrib.auth.decorators import login_required
#from braces.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

def index(request):
    return HttpResponse('hello')
	
@login_required(login_url='accounts:login')
def checkin(request):
    att=Event()
    current_time = datetime.now()
    att.start_time = current_time
    att.user = request.user
    att.save()
    #messages.success(request, 'You are checked in Successfully')
    return HttpResponseRedirect(reverse('cal:calendar')) #return redirect(calendar)  #return HttpResponse('You are checked in') leave

@login_required(login_url='accounts:login')
def checkout(request,pk):
    att=Event.objects.get(id=pk)
    current_time = datetime.now()
    att.end_time = current_time
    att.save()
    return HttpResponseRedirect(reverse('cal:calendar'))
 
#@login_required 
class CalendarView(generic.ListView):
    model = Event#(user=request.user)
    #queryset = Event.objects.filter(user=request.user)
    template_name = 'cal/calendar.html'
    def get_queryset(self):
        return Event.objects.filter(user=self.request.user)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #owner = Event(user=self.request.user)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month) #,owner)
        html_cal = cal.formatmonth(withyear=True)
        #Event.objects.filter(user=self.request.user)
        today = date.today()
        check_in_user = Event.objects.filter(user=self.request.user)
        #print(check_in_user)
        checkin_date = ''
        if not check_in_user.filter(start_time__year=today.year, start_time__month=today.month, start_time__day=today.day).exists():
            #Event.objects.filter(user=self.request.user).exists():
            checkin_date = None
        else:
            #checkin_date = Event(user=self.request.user)
            checkin_date = Event.objects.get(user=self.request.user,start_time__year=today.year, start_time__month=today.month, start_time__day=today.day)
            checkin_date.user = self.request.user         #(Q(start_time__year=today.year, start_time__month=today.month, start_time__day=today.day)| Q(user = self.request.user))
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['checkin_date'] = checkin_date
        return context
    


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Leave()
    if event_id:
        instance = get_object_or_404(Leave, pk=event_id)
    else:
        instance = Leave()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        s = form.save(commit = False)
        s.user = request.user
        s.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})

@login_required(login_url='accounts:login')
def view_attendance(request,pk):
    attendance = Event.objects.filter(user_id = pk)
    usr = User.objects.get(id = pk)
    return render(request, 'view_attendance.html',{'att':attendance,'usr':usr})

@login_required(login_url='accounts:login')    
def view_leave(request,pk):
    attendance = Leave.objects.filter(user_id = pk)
    usr = User.objects.get(id = pk)
    return render(request, 'view_leave.html',{'att':attendance,'usr':usr})

cal/templates/cal/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>
 
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

cal/templates/cal/calendar.html
<!DOCTYPE html>
{% load static %}
<html>
<title>DMS|Dashboard</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/w3_fonts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/w3_awsome_font.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <!-- Calendar CSS -->
<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"-->
<!--    crossorigin="anonymous">-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}


</style>

<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">

  <button class="w3-bar-item w3-button w3-left w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <a href="{%url 'upload:file_upload'%}" class="w3-bar-item w3-button">Document Management System</a>
 <a href="{%url 'accounts:logout'%}" class="w3-bar-item w3-right" >Logout</a>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
	{% if user.userdetails.Img %}
	<img src="{{user.userdetails.Img.url}}" class="w3-circle w3-margin-right" style="width:66px">"
	{% else %}
	<img src="{% static 'images/gallery4.jpg'%}" class="w3-circle w3-margin-right" style="width:86px">
	{% endif %}
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Welcome, <strong>{{ user.first_name }}</strong></span><!--
	  <span>Welcome, <strong>{{ user.profile.Role }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>-->
    </div>
  </div>
  <hr>
<!--  <div class="w3-container">-->
<!--    <h5>Dashboard</h5>-->
<!--  </div>-->
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="{%url 'cal:calendar'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Attendance</a>
	{% if user.profile.Role_id != 2 %}
	<a href="{%url 'upload:user_list_new'%}" class="w3-bar-item w3-button w3-padding "><i class="fa fa-users fa-fw"></i>Manage user</a>
	{% else %}
	<a href="{%url 'upload:view_profile'%}" class="w3-bar-item w3-button w3-padding "><i class="fa fa-users fa-fw"></i>View Profile</a>
	{% endif %}
    <a href="{%url 'upload:search_files'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-search fa-fw"></i>  Search file</a>
	<a href="{%url 'upload:files'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-folder-open fa-fw"></i>Upload files</a>
    <a href="{%url 'upload:basic_upload'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-folder-open fa-fw"></i>  Multiple upload</a>
    <a href="{%url 'upload:drag_and_drop_upload'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-folder-open fa-fw"></i>  Drag and Drop upload</a>
   <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>  Geo</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Orders</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  News</a>
	<a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>-->
<!--    <a href="{%url 'upload:Contacts'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-book fa-fw"></i>  Contacts</a>-->
    <a href="{%url 'upload:Contacts'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-book fa-fw"></i>  Contacts</a>
    <a href="{%url 'upload:add_file'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-plus fa-fw"></i>Folder</a>
<!--     <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  History</a>-->

  </div>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:310px;margin-top:43px;">
<br>
<div class="clearfix">

	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	{% now "Y-m-d" as todays_date %}
<!--	{{ checkin_date.start_time|date:'Y-m-d' }} {{ todays_date }}{{ checkin_date.user }} -->
	{% if checkin_date.start_time|date:'Y-m-d' != todays_date %}
	   <a class="btn btn-info left" href="{% url 'cal:check_in' %}?{{ prev_month }}"> check in </a>
	{% elif checkin_date.end_time|date:'Y-m-d' != todays_date %}
	   <a class="btn btn-info left" href="{% url 'cal:check_out' checkin_date.id %}"> check out </a>
	   {% else %}
	   <a > Your attendance is marked for today</a>
	{% endif %}
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> Leave request </a>

</div>




{{ calendar }}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script>

// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>



  {% block script %}
  {% endblock %}
</div>

</body>

</html>

cal/templates/cal/calendar1.html
{% extends 'dash.html' %} 

<html>


{% block content %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">

	{% block css %}
	{% load  static %}
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  {% endblock css %}
  <title>Django Calendar App</title>
</head>

<body>
<h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	{% now "Y-m-d" as todays_date %}
	
	<!-- {{ checkin_date.start_time|date:'Y-m-d' }} {{ todays_date }}{{ checkin_date.id }} {{ checkin_date.user }}-->
	{% if checkin_date.start_time|date:'Y-m-d' != todays_date %}
	   <a class="btn btn-info left" href="{% url 'cal:check_in' %}?{{ prev_month }}"> check in </a>
	{% elif checkin_date.end_time|date:'Y-m-d' != todays_date %}   
	   <a class="btn btn-info left" href="{% url 'cal:check_out' checkin_date.id %}"> check out </a>
	   {% else %} 
	   <a > Your attendance is marked for today</a>
	{% endif %}
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> Leave request </a>
	</div>
	{{ calendar }}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>
</html>
{% endblock %}

cal/templates/cal/event.html
{% extends 'dash1.html' %} 

{% block title %}
Leave Request
{% endblock %}

{% block content %}
<br>
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}