accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    
	path('',views.log_in, name='login'),
	path('logout/',views.log_out, name='logout'),
	path('password/', views.change_password, name='change_password'),
]

cal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
	url(r'^checkin/$',views.checkin, name='check_in'),
	path('checkout/<int:pk>/', views.checkout, name='check_out'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
	# url(r'^Leaveview/$', views.LeaveView.as_view(), name='LeaveView'),
    url(r'^leave/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<Leave_id>\d+)/$', views.event, name='event_edit'),
	path('view_attendance/<int:pk>/', views.view_attendance, name='view_attendance'),
	path('view_leave/<int:pk>/',views.view_leave,name='view_leave'),
]
#path('edit/<int:pk>/', views.Editfiles,name='Editfiles'),

testsql/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
	#path('base/', views.base, name='layout'),
	path('', include('accounts.urls')),
	#path('',views.log_in, name='login'),
	#path('logout/',views.log_out, name='logout'),
	#path('home/', include('DMS.urls')),
	path('upload/', include('upload.urls')),
	path('cal/', include('cal.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .import views
#from django.views.generic import TemplateView
from .views import BasicUploadView, ProgressBarUploadView,DragAndDropUploadView

app_name='upload'
urlpatterns = [
	
	path('', views.file_upload,name='file_upload'),
	path('folder/', views.create_folder,name='folder'),
	path('add_file/', views.add_file, name='add_file'),
	path('<id>/remove_folder/',views.remove_folder,name='remove_folder'),
	path('<id>/rename_folder/',views.rename_folder,name='rename_folder'),
	path('<id>/folder_detail',views.folder_detail,name="folder_detail"),
	path('files/', views.upload_files,name='files'),
	path('search/', views.search_file,name='search_files'),
	path('searchfile/', views.Search_File_New,name='search_file_new'),
	path('filterfiles/', views.filterfiles,name='filterfiles'),
	#path('files/<int:pk>/', views.FileUpdateView.as_view(),name='edit_file'),
	path('edit/<int:pk>/', views.Editfiles,name='Editfiles'),
	#path('edit_save/<int:pk>/', views.Editfiles_save,name='Editfiles_save'),
	path('view/<int:pk>/', views.Viewfiles,name='Viewfiles'),
	path('Download/<int:pk>/', views.Downloadfiles,name='Downloadfiles'),
	path('signup/',views.signup,name='signup'),
	path('manage_user/',views.manage_user,name='manage_user'),
	path('users/',views.user_list_new,name='user_list_new'),
	path('modify/<int:pk>/',views.modify_user,name='modify_user'),
	path('Contacts/',views.UserContacts,name='Contacts'),
	path('addContacts/',views.ADDContacts,name='addContacts'),
	path('search_contact/',views.Search_Contact,name='Search_Cont'),
	path('clear/', views.clear_database, name='clear_database'),
    #path('', BasicFileUploadView.as_view(), name='basic-upload'),
	path('basic/', BasicUploadView.as_view(), name='basic_upload'),
	#path('multiple/', MultipleUploadView.as_view(), name='multiple_upload'),
	path('progressbar/', ProgressBarUploadView.as_view(), name='progress_bar_upload'),
	path('draganddrop/', DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
	path('multipleupload/', views.multipleupload, name='multipleupload'), 
	path('view_profile/', views.view_profile, name='view_profile'),
	#path('change_profile_image/', views.change_profile_image, name='change_profile_image'),
	path('update_profile_image/', views.update_profile_image, name='update_profile_image'),
	path('view_user_profile/<int:pk>/', views.view_user_profile, name='view_user_profile'),

	
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

upload/views.py
import shutil

from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views.generic import DetailView

from .forms import FileForm, AddUserForm, EditFileForm, ModifyForm, ContactForm, CreateUserForm, PhotoForm, File_Form, \
    UserdetailsForm, ProfileImage, DirectoryForm

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from .forms import SignUpForm,Create_folderForm
import os
from django.http import JsonResponse
import datetime
from datetime import date
from django.contrib import messages
from .models import Files, Profile, Contacts, Userdetails, Create_folder, Directory, Rename
from django.views import View  #from django.views.generic import UpdateView
from django.urls import reverse_lazy
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ValidationError


@login_required(login_url='accounts:login')
def file_upload(request):
    c=Files
    c.count_pdf=Files.objects.filter(title=1).count()
    c.count_doc=Files.objects.filter(title=2).count()
    c.count_excel=Files.objects.filter(title=3).count()
    c.count_img=Files.objects.filter(title=4).count()
    #aa=[7,8,9,]
    #print(aa)
    #u=request.user
    #r=AddDetails(user_id=u)
    #print(request.user.AddDetails.Gender)
    return render(request,"dash.html",{'c':c,
    #'u':u,
    })


@login_required(login_url='accounts:login')
def upload_files(request):
    #file_form=FileForm()
    a=[1,2,3,4,5]
    #print(a)
    if request.method == 'POST':
        file_form = FileForm(request.POST, request.FILES)
        #s=file_form
        #print(a)
        
        file_form.file=request.FILES['file']
        value=file_form.file
        ext = os.path.splitext(value.name)[1]
        if ext == '.pdf':
            file_form.title=1
        elif ext == '.doc' or ext=='.docx':
            file_form.title=2
        elif ext=='.xlsx' or ext=='.csv':
            file_form.title=3
        elif ext=='.jpg' or ext=='.png' or ext=='.bmp':
            file_form.title=4
        #print(ext)
        if file_form.is_valid():
            #print(file_form.title)
            s = file_form.save(commit=False)
            s.title = file_form.title
            s.user = request.user
            s.is_multiple = 0
            s.save()
            return redirect('upload:search_files')
            #return render(request, 'search.html',{'error':'File uploaded successfully'})
           #return render(request, 'home.html')#HttpResponseRedirect('success')
    else:
        file_form = FileForm()
        #print(a)
    #return HttpResponseRedirect('ok')
    #return HttpResponseRedirect('login')
    return render(request, 'upload_files.html',{'file_form':file_form})#HttpResponseRedirect('success')
    #return render(request,"create_folder.html")

@login_required(login_url='accounts:login')
def search_file(request):
    c=Files
    c=Files.objects.order_by('-uploaded_at')[:10] #.all #filter().all #order_by('-uploaded_at')[:10] #all

    # c.pdf=Files.objects.filter(title=1).count()
    # c.count_doc=Files.objects.filter(title=2).count()
    # c.count_excel=Files.objects.filter(title=3).count()
    # c.count_img=Files.objects.filter(title=4).count()
    return render(request, 'search.html',{'c':c})

                                                # class FileUpdateView(UpdateView):
                                                    # #context_object_name = pk
                                                    # model = Files
                                                    # form_class = FileForm
                                                    # #fields = ['Name', 'Description','File','uploaded_at']
                                                    # #print(model.id)
                                                    # template_name = "Files_form.html"
                                                    # success_url = reverse_lazy('upload:Editfiles_save') #,'model.id')

    

        
@login_required(login_url='accounts:login')
def Editfiles(request,pk):
    item = Files.objects.get(id=pk)
    aa=[7,8,9,]
    #print(aa)
    if request.method == 'POST':
        file_form = FileForm(request.POST, request.FILES,instance=item)
        file_form.user = request.user
        #print(aa)
        if file_form.is_valid():
            #print(aa)
            file_form.file=request.FILES['file']
            value=file_form.file
            ext = os.path.splitext(value.name)[1]
            if ext == '.pdf':
                file_form.title=1
            elif ext == '.doc' or ext=='.docx':
                file_form.title=2
            elif ext=='.xlsx' or ext=='.csv':
                file_form.title=3
            elif ext=='.jpg' or ext=='.png' or ext=='.bmp':
                file_form.title=4
            #print(ext)
            #print(file_form.title)
            s=file_form.save(commit=False)
            s.title=file_form.title
            #print(aa)
            s.id = item.id
            s.save()
            return redirect('upload:search_files')
            #return render(request, 'Files_form.html',{'error':'File uploaded successfully'})
           #return render(request, 'home.html')#HttpResponseRedirect('success')
    else:
        file_form = FileForm(instance=item)
        #a=item.File #request.FILES.get['File']
        args = {}
        args.update(csrf(request))
        args['file_form'] = file_form
        #print(item.Name)
        #print(aa)
    return render(request, 'Files_form.html',args,{'item':item})#HttpResponseRedirect('success')

@login_required(login_url='accounts:login')
def Viewfiles(request,pk):
    item = Files.objects.get(id=pk)
    item.name=item.name
    item.uploaded_at=item.uploaded_at
    item.description=item.description
    item.file=item.file
    return render(request, 'Viewfiles.html',{'item':item})

@login_required(login_url='accounts:login')
def Downloadfiles(request,pk):
    item = Files.objects.get(id=pk)
    item.file=item.file
    return render(request, 'Downloadfiles.html',{'item':item})

# def signup(request):
    # if request.method == 'POST':
        # usr = Profile()
        # form_adduser= CreateUserForm(request.POST or None)
        # try:
            # user = User.objects.get(username=request.POST['username'])
            # return render(request, 'signup1.html', {'error':'Username is already taken'})
        # except User.DoesNotExist:
            # User.username = request.POST['username']
            # #User.first_name = request.POST['first_name']
            # #User.last_name = request.POST['last_name']
            # #User.email = request.POST['email']
            # print(User.email)
            # User.password = 'Pro123!@#'
            # user = User.objects.create_user(User.username, User.password)
            # #User.save()
            # s = form_adduser.save(commit = False)
            # s.user = User
            # s.save()
            # return render(request, 'manage_user.html') #return redirect('upload/manage_user')


        # # else:
            # # return render(request, 'signup1.html', {'error':'Password doesn\'t matched'})

    # else:
        # form_adduser= CreateUserForm(request.POST or None)
        # return render(request, 'signup1.html',{'form_adduser':form_adduser})
@login_required(login_url='accounts:login')
def signup(request):
    #a=[1,2,3,4,5,6,7]
    if request.method == 'POST':
        form = SignUpForm(request.POST or None)
        form.password1 = request.POST.get('password1')
        print(form.password1)
        if form.is_valid(): # and form_adduser.is_valid():
            
            user = form.save()
            user.refresh_from_db()
            user.profile.Gender = form.cleaned_data.get('Gender')
            user.profile.Role = form.cleaned_data.get('Role')
            username = form.cleaned_data.get('username')
            #user.set_password('Pro123!@#')
            user.save() 
            #raw_password = form.password1   user.set_password(self.cleaned_data['new_password1'])
            #print(raw_password)
             
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            messages.success(request, ('New user successfully created!'))
            
            return redirect('upload:user_list_new')
        
    else:
        form = SignUpForm()
        #form_adduser= CreateUserForm()
    return render(request, 'signup.html', {'form': form}) #,'form_adduser': form_adduser})

@login_required(login_url='accounts:login')
def manage_user(request):
    
    return render(request, 'manage_user.html')
    
@login_required(login_url='accounts:login')
def user_list_new(request):
    us_er=User
    us_er.total = us_er.objects.all
    return render(request, 'user_list_new.html',{'us_er':us_er})

@login_required(login_url='accounts:login')
def modify_user(request,pk):
    usr=User.objects.get(id=pk)                          #form['fieldname'].field.widget.attr['readonly'] = 'readonly'
    usr.ID = usr.id
    usr.Name= usr.username
    usr.first_name=usr.first_name
    usr.last_name=usr.last_name
    usr.email=usr.email
    #usr.Role=usr.Profile.Role
    #print(usr.Role)
    if request.method == 'POST':
        #file_form = FileForm(request.POST, request.FILES)
        form_adduser= AddUserForm(request.POST, request.FILES)
        #form_adduser.user = usr.id
        if form_adduser.is_valid():
            #form_adduser.Img = request.FILES['Img']            
            #print(a)
            s=form_adduser.save(commit = False)
            s.user = usr
            s.save()
            messages.success(request, ('User successfully updated!'))
            return render(request, 'manage_user.html')
        
    else:
        #form = ModifyForm(instance=usr)
        form_adduser= AddUserForm()

upload/templates/Search_File_New.html
{% extends "dash.html" %}
{% load static %}
{% block content %}
<html>
<title>DMS|Search</title>
<style>
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 0px 9px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
 select {
        width:100px;
		margin: 10px;
    }
 select:focus {
        min-width: 100px;
        width: auto;
    }
</style>
<div class="container">
<!--<h1>Files in the system are:</h1>-->
<br>
<form action="/upload/searchfile/" method="GET">
    File Name: <input type="text" name="Name" />
	From Date: <input type="date" name="from_date" />
	To Date: <input type="date" name="to_date" />
    <button type="submit" class="button">search</button>
   </form>
 <form action="/upload/filterfiles/" method="GET">   
   Filter Files: <select name="filterfiles">  
        <option value="all"> All files </option>
		<option value="pdf"> PDF </option>
        <option value="word"> Word </option>
		<option value="image"> Image </option>
		<option value="excel"> Excel </option>
     </select> 
	 <button type="submit" class="button">Filter</button> <br>
</form>
<em>Files in the system are:</em>
    <div class=" w-75" align="center">

    <table class="table  ml-5 text-center shadow bg-white rounded  ml-5 " cellpadding="" cellspacing="" >
    <thead>
      <tr>
        <th>File Name</th>
        <th>File</th>
        <th>uploaded date</th>
		<th>Edit</th>
		<th>View</th>
		<th>Download</th>
      </tr>
    </thead>
	<tbody>
      {% for f in results %}
        <tr>
          <td>{{ f.name }}</a></td>
          <td>{{ f.file }}</td>
          <td>{{ f.uploaded_at }}</td>
          <td><a href="{% url 'upload:Editfiles' f.pk %}"></a>Edit</td>
		  <td><a href="{% url 'upload:Viewfiles' f.pk %}"></a>View</td>
		  <td><a href="{% url 'upload:Downloadfiles' f.pk %}"></a>Download</td>
		  <!--<td><embed src="{{f.File.url}}" type="application/pdf" height="100px" width="100px"></td>-->
        </tr>
      {% endfor %}
    </tbody>
  </table>
    </div>
</div>
</html>

{% endblock %}

upload/templates/dash.html
<!DOCTYPE html>
{% load static %}
<html>
<title>DMS|Dashboard</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/w3_fonts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/w3_awsome_font.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}


</style>

<body class="w3-light-grey">
   
<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
   
  <button class="w3-bar-item w3-button w3-left w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <a href="{%url 'upload:file_upload'%}" class="w3-bar-item w3-button">Document Management System</a> 
 <a href="{%url 'accounts:logout'%}" class="w3-bar-item w3-right" >Logout</a>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
	{% if user.userdetails.Img %}  
	<img src="{{user.userdetails.Img.url}}" class="w3-circle w3-margin-right" style="width:66px">"
	{% else %}
	<img src="{% static 'images/gallery4.jpg'%}" class="w3-circle w3-margin-right" style="width:86px">
	{% endif %}
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Welcome, <strong>{{ user.first_name }}</strong></span><!--
	  <span>Welcome, <strong>{{ user.profile.Role }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>-->
    </div>
  </div>
  <hr>
<!--  <div class="w3-container">-->
<!--    <h5>Dashboard</h5>-->
<!--  </div>-->
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="{%url 'cal:calendar'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-calendar fa-fw"></i>  Attendance</a>
	{% if user.profile.Role_id != 2 %}
	<a href="{%url 'upload:user_list_new'%}" class="w3-bar-item w3-button w3-padding "><i class="fa fa-users fa-fw"></i>Manage user</a>
	{% else %}
	<a href="{%url 'upload:view_profile'%}" class="w3-bar-item w3-button w3-padding "><i class="fa fa-users fa-fw"></i>View Profile</a>
	{% endif %}
    <a href="{%url 'upload:search_files'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-search fa-fw"></i>  Search file</a>
	<a href="{%url 'upload:files'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-folder-open fa-fw"></i>Upload files</a>
    <a href="{%url 'upload:basic_upload'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-folder-open fa-fw"></i>  Multiple upload</a>
    <a href="{%url 'upload:drag_and_drop_upload'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-folder-open fa-fw"></i>  Drag and Drop upload</a>   
   <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>  Geo</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Orders</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  News</a>
	<a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>-->
<!--    <a href="{%url 'upload:Contacts'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-book fa-fw"></i>  Contacts</a>-->
    <a href="{%url 'upload:Contacts'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-address-book fa-fw"></i>  Contacts</a>
    <a href="{%url 'upload:add_file'%}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-plus fa-fw"></i>Folder</a>
<!--     <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  History</a>-->
    
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:350px;margin-top:43px;">
{% block content %}
  <!-- Header -->
  <header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
  </header>

  <div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter">
      <div class="w3-container w3-red w3-padding-16">
        <div class="w3-left"><i class="fa fa-file-pdf-o w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{c.count_pdf}}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Pdf</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-blue w3-padding-16">
        <div class="w3-left"><i class="fa fa-file-word-o w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{c.count_doc}}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Word</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-teal w3-padding-16">
        <div class="w3-left"><i class="fa fa-file-picture-o w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{c.count_img}}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Images</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-orange w3-text-white w3-padding-16">
        <div class="w3-left"><i class="fa fa-file-excel-o w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{c.count_excel}}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Excel</h4>
      </div>
    </div>
  </div>

  
  <hr>
  <div class="w3-container">
    <h5>General Stats</h5>
    <p> words</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-green" style="width:{{c.count_doc}}%">{{c.count_doc}}</div>
    </div>

    <p> pdf</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-orange" style="width:{{c.count_pdf}}%">{{c.count_pdf}}</div>
    </div>

    <p> image</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-red" style="width:{{c.count_img}}%">{{c.count_img}}</div>
    </div>

     <p>excel</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-blue" style="width:{{c.count_excel}}%">{{c.count_excel}}</div>
    </div>
  </div>
  <hr>



  <!-- Footer -->
  

  <!-- End page content -->
</div>
 {% endblock %}

   
<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>
<footer class="w3-container w3-center">
    &copy Prodigy Technosys {% now "Y"%}
  </footer>

  
</body>

</html>

upload/templates/manage_user.html
{% extends "dash.html" %}
{% load static %}
{% block content %}

<div class="container">
<br><br>
<p><a href="{% url 'upload:user_list_new' %}">Users list</a></p>
 
<p><a href="{% url 'upload:signup' %}">Create new user</a></p>
</div>
{% endblock %}

upload/templates/user_list_new.html
<br>
{% extends "dash.html" %}
{% block content %}
<head>
<style>
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 0px 9px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>
<p><a href="{% url 'upload:signup' %}" class="button">Create new user</a></p><br>
<em> All users in the system </em>

  
	<table style="width:90%" class="table  ml-5 text-center shadow bg-white rounded  ml-5 ">
    <thead>
      <tr class="ml-2">
        <th>ID</th>
        <th>Username</th>
        <th>first name</th>
		<th>last name</th>
		<th>Role</th>
		<th>Email address</th>
		<th>View Attendance</th>
		<th>View Leave</th>
		
	  </tr>
    </thead>
	{{ us_er.total.Role_id}}
	<tbody>
      {% for i in us_er.total %}
        <tr>
          <td>{{ i.id }}</a></td>
          <td><a href="{% url 'upload:view_user_profile' i.pk %}">{{i.username }}</a></td>
          <td>{{ i.first_name }}</td>
          <td>{{i.last_name}}</td>
		  <td>{{ i.profile.Role }}</td>
		  <td>{{i.email}}</td>
		<!--  <td>{{i.Role_id}}</td>-->
		  <td><a href="{% url 'cal:view_attendance' i.pk %}">Attendance</a></td>
		  <td><a href="{% url 'cal:view_leave' i.pk %}">View Leave</a></td>
		<!--  <td><a href="{% url 'upload:modify_user' i.pk %}">View Leave</a></td>
		  <td><embed src="{{f.File.url}}" type="application/pdf" height="100px" width="100px"></td>-->
        </tr>
      {% endfor %}
	  
    </tbody>
	</table>
	{% endblock %}