accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    
	path('',views.log_in, name='login'),
	path('logout/',views.log_out, name='logout'),
	path('password/', views.change_password, name='change_password'),
]

cal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
	url(r'^checkin/$',views.checkin, name='check_in'),
	path('checkout/<int:pk>/', views.checkout, name='check_out'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
	# url(r'^Leaveview/$', views.LeaveView.as_view(), name='LeaveView'),
    url(r'^leave/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<Leave_id>\d+)/$', views.event, name='event_edit'),
	path('view_attendance/<int:pk>/', views.view_attendance, name='view_attendance'),
	path('view_leave/<int:pk>/',views.view_leave,name='view_leave'),
]
#path('edit/<int:pk>/', views.Editfiles,name='Editfiles'),

testsql/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
	#path('base/', views.base, name='layout'),
	path('', include('accounts.urls')),
	#path('',views.log_in, name='login'),
	#path('logout/',views.log_out, name='logout'),
	#path('home/', include('DMS.urls')),
	path('upload/', include('upload.urls')),
	path('cal/', include('cal.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .import views
#from django.views.generic import TemplateView
from .views import BasicUploadView, ProgressBarUploadView,DragAndDropUploadView

app_name='upload'
urlpatterns = [
	
	path('', views.file_upload,name='file_upload'),
	path('folder/', views.create_folder,name='folder'),
	path('add_file/', views.add_file, name='add_file'),
	path('<id>/remove_folder/',views.remove_folder,name='remove_folder'),
	path('<id>/rename_folder/',views.rename_folder,name='rename_folder'),
	path('<id>/folder_detail',views.folder_detail,name="folder_detail"),
	path('files/', views.upload_files,name='files'),
	path('search/', views.search_file,name='search_files'),
	path('searchfile/', views.Search_File_New,name='search_file_new'),
	path('filterfiles/', views.filterfiles,name='filterfiles'),
	#path('files/<int:pk>/', views.FileUpdateView.as_view(),name='edit_file'),
	path('edit/<int:pk>/', views.Editfiles,name='Editfiles'),
	#path('edit_save/<int:pk>/', views.Editfiles_save,name='Editfiles_save'),
	path('view/<int:pk>/', views.Viewfiles,name='Viewfiles'),
	path('Download/<int:pk>/', views.Downloadfiles,name='Downloadfiles'),
	path('signup/',views.signup,name='signup'),
	path('manage_user/',views.manage_user,name='manage_user'),
	path('users/',views.user_list_new,name='user_list_new'),
	path('modify/<int:pk>/',views.modify_user,name='modify_user'),
	path('Contacts/',views.UserContacts,name='Contacts'),
	path('addContacts/',views.ADDContacts,name='addContacts'),
	path('search_contact/',views.Search_Contact,name='Search_Cont'),
	path('clear/', views.clear_database, name='clear_database'),
    #path('', BasicFileUploadView.as_view(), name='basic-upload'),
	path('basic/', BasicUploadView.as_view(), name='basic_upload'),
	#path('multiple/', MultipleUploadView.as_view(), name='multiple_upload'),
	path('progressbar/', ProgressBarUploadView.as_view(), name='progress_bar_upload'),
	path('draganddrop/', DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
	path('multipleupload/', views.multipleupload, name='multipleupload'), 
	path('view_profile/', views.view_profile, name='view_profile'),
	#path('change_profile_image/', views.change_profile_image, name='change_profile_image'),
	path('update_profile_image/', views.update_profile_image, name='update_profile_image'),
	path('view_user_profile/<int:pk>/', views.view_user_profile, name='view_user_profile'),

	
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    username = forms.CharField(label=("Username"),max_length=100) #,placeholder = 'Enter username') 
	#, widgets=forms.textinput)
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','password')

accounts/views.py
from django.contrib.auth import login, authenticate, logout
from .forms import LoginForm  #,SignUpForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

# def base(request):
	# if request.session.get("islogin"):
		# return render(request,"dashboard.html")
	# else:
	#	return render(request,"login.html")

def log_in(request):
	if request.method == 'POST':
		form = LoginForm(request.POST or None)
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		# if user.last_login is None:
		    # return redirect('accounts:change_password')
		if user is not None:
			login(request, user)
			return redirect('upload:file_upload') #render(request, "dash.html")
		else:
			form = LoginForm()
			return render(request, 'login_mine.html',{'error':'username or password is incorrect!','form':form})
	else:
		form = LoginForm()
		return render(request, 'login_mine.html',{'form':form})
def log_out(request):
		#request.session.flush()
	if request.method=='GET':	#why POST method is not working i don't know need to find it out
		
		logout(request)
		
		#mykey=request.session['mykey']
		#del request.session['mykey']
	return redirect('accounts:login')

@login_required(login_url='accounts:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('upload:view_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })

accounts/templates/Add_user.html
<h2>Add user</h2>
  <form method="post">
    {% csrf_token %}
    {{ AdduserForm.as_p }}
	<!--{{ location_form.as_p }}-->
    <button type="submit">submit</button>
  </form>

accounts/templates/Address_dropdown_list.html
<select name="Country" id="id_country" required>
                <option value="0" > Select </option>
                {% for obj in Prov %}
                <option value="{{ obj.id }}">{{ obj.name }} </option>
                {% endfor %}
            </select>

accounts/templates/Address_test.html
<h2>Address</h2>

  <form method="post" id="AddressForm" address-url="{% url 'DMS:ajax_address' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ addressform.as_table }}
	  
    </table>
	
    <button type="submit">Save</button>
    
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_Country").change(function () {
      var url = $("#AddressForm").attr("address-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input
      
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId 
            document.write('country')		  // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_Province").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

accounts/templates/ajax_address.html
<h2>Address</h2>

  <form method="post" id="MunicipalityForm" address-url="{% url 'DMS:ajax_address' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ addressform.as_table }}
    </table>
    <button type="submit">Save</button>
    
  </form>

  

accounts/templates/change_password.html
{% extends "login_mine.html" %}
{% block content %}

<head>
<style>
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 0px 9px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 14px;
  margin: 4px 2px;
  cursor: pointer;
}
</style>
</head>

<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit" class="button">Save changes</button>
</form>

{% endblock %}

accounts/templates/country.html
<h2>Add Address</h2>
<form method="post">
    {% csrf_token %}
    {{ addressform.as_p }}
	<!--{{ location_form.as_p }}-->
    <button type="submit">submit</button>
	
  </form>
 
 <!--<select name="Country" id="id_country" required>
                <option value="0" > Select </option>
                {% for obj in Prov %}
                <option value="{{ obj.name }}">{{ obj.name }} </option>
                {% endfor %}
            </select>
			-->

accounts/templates/dashboard.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right">Logo</span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Welcome, <strong>Mike</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-users fa-fw"></i>  Overview</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i>  Views</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  Traffic</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>  Geo</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Orders</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  News</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bank fa-fw"></i>  General</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  History</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">

  <!-- Header -->
  <header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
  </header>

  <div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter">
      <div class="w3-container w3-red w3-padding-16">
        <div class="w3-left"><i class="fa fa-comment w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>52</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Messages</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-blue w3-padding-16">
        <div class="w3-left"><i class="fa fa-eye w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>99</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Views</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-teal w3-padding-16">
        <div class="w3-left"><i class="fa fa-share-alt w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>23</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Shares</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-orange w3-text-white w3-padding-16">
        <div class="w3-left"><i class="fa fa-users w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>50</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Users</h4>
      </div>
    </div>
  </div>

  <div class="w3-panel">
    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-third">
        <h5>Regions</h5>
        <img src="/w3images/region.jpg" style="width:100%" alt="Google Regional Map">
      </div>
      <div class="w3-twothird">
        <h5>Feeds</h5>
        <table class="w3-table w3-striped w3-white">
          <tr>
            <td><i class="fa fa-user w3-text-blue w3-large"></i></td>
            <td>New record, over 90 views.</td>
            <td><i>10 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-bell w3-text-red w3-large"></i></td>
            <td>Database error.</td>
            <td><i>15 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-users w3-text-yellow w3-large"></i></td>
            <td>New record, over 40 users.</td>
            <td><i>17 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-comment w3-text-red w3-large"></i></td>
            <td>New comments.</td>
            <td><i>25 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-bookmark w3-text-blue w3-large"></i></td>
            <td>Check transactions.</td>
            <td><i>28 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-laptop w3-text-red w3-large"></i></td>
            <td>CPU overload.</td>
            <td><i>35 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-share-alt w3-text-green w3-large"></i></td>
            <td>New shares.</td>
            <td><i>39 mins</i></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>General Stats</h5>
    <p>New Visitors</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-green" style="width:25%">+25%</div>
    </div>

    <p>New Users</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-orange" style="width:50%">50%</div>
    </div>

    <p>Bounce Rate</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-red" style="width:75%">75%</div>
    </div>
  </div>
  <hr>

  <div class="w3-container">
    <h5>Countries</h5>
    <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
      <tr>
        <td>United States</td>
        <td>65%</td>
      </tr>
      <tr>
        <td>UK</td>
        <td>15.7%</td>
      </tr>
      <tr>
        <td>Russia</td>
        <td>5.6%</td>
      </tr>
      <tr>
        <td>Spain</td>
        <td>2.1%</td>
      </tr>
      <tr>
        <td>India</td>
        <td>1.9%</td>
      </tr>
      <tr>
        <td>France</td>
        <td>1.5%</td>
      </tr>
    </table><br>
    <button class="w3-button w3-dark-grey">More Countries  <i class="fa fa-arrow-right"></i></button>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Recent Users</h5>
    <ul class="w3-ul w3-card-4 w3-white">
      <li class="w3-padding-16">
        <img src="/w3images/avatar2.png" class="w3-left w3-circle w3-margin-right" style="width:35px">
        <span class="w3-xlarge">Mike</span><br>
      </li>
      <li class="w3-padding-16">
        <img src="/w3images/avatar5.png" class="w3-left w3-circle w3-margin-right" style="width:35px">
        <span class="w3-xlarge">Jill</span><br>
      </li>
      <li class="w3-padding-16">
        <img src="/w3images/avatar6.png" class="w3-left w3-circle w3-margin-right" style="width:35px">
        <span class="w3-xlarge">Jane</span><br>
      </li>
    </ul>
  </div>
  <hr>

  <div class="w3-container">
    <h5>Recent Comments</h5>
    <div class="w3-row">
      <div class="w3-col m2 text-center">
        <img class="w3-circle" src="/w3images/avatar3.png" style="width:96px;height:96px">
      </div>
      <div class="w3-col m10 w3-container">
        <h4>John <span class="w3-opacity w3-medium">Sep 29, 2014, 9:12 PM</span></h4>
        <p>Keep up the GREAT work! I am cheering for you!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><br>
      </div>
    </div>

    <div class="w3-row">
      <div class="w3-col m2 text-center">
        <img class="w3-circle" src="/w3images/avatar1.png" style="width:96px;height:96px">
      </div>
      <div class="w3-col m10 w3-container">
        <h4>Bo <span class="w3-opacity w3-medium">Sep 28, 2014, 10:15 PM</span></h4>
        <p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><br>
      </div>
    </div>
  </div>
  <br>
  <div class="w3-container w3-dark-grey w3-padding-32">
    <div class="w3-row">
      <div class="w3-container w3-third">
        <h5 class="w3-bottombar w3-border-green">Demographic</h5>
        <p>Language</p>
        <p>Country</p>
        <p>City</p>
      </div>
      <div class="w3-container w3-third">
        <h5 class="w3-bottombar w3-border-red">System</h5>
        <p>Browser</p>
        <p>OS</p>
        <p>More</p>
      </div>
      <div class="w3-container w3-third">
        <h5 class="w3-bottombar w3-border-orange">Target</h5>
        <p>Users</p>
        <p>Active</p>
        <p>Geo</p>
        <p>Interests</p>
      </div>
    </div>
  </div>

  <!-- Footer -->
  <footer class="w3-container w3-padding-16 w3-light-grey">
    <h4>FOOTER</h4>
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
  </footer>

  <!-- End page content -->
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>

</body>
</html>

accounts/templates/index.html
<h1>Successfully created user</h1> 

accounts/templates/login.html
{%load static%}
<html>
<!--{% block title %}Login{% endblock %}-->
{{error}}
  <h2>Login</h2>
  <form method="post" action="{% url 'login'%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>

</html>

accounts/templates/login1.html
<html>
{%load static%}
<style>

.center {
  margin: 150 auto;
  width: 30%;
  border: 2px solid #73AD21;
  padding: 27px;
    }
</style>
   <header>
   
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Document Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          

            
            <a class="nav-item nav-link active" href="{%url 'upload:file_upload'%}">upload</a>
            <a class="nav-item nav-link active" href="{%url 'upload:folder'%}" >Add Folder</a>
			<a class="nav-item nav-link active" href="{%url 'upload:files'%}" >Upload files</a>
          
        </div>
      </nav>
</header>

<body>
<br></br>
<br></br>
 <p><a href="{% url 'DMS:adduser' %}">Add user</a></p>
 <p><a href="{% url 'DMS:user_list' %}">user_list</a></p>
 <p><a href="{% url 'DMS:Address_detail' %}">Address_detail</a></p>

<h1 align="center">Add user</h1>
<div class="center" >
<h2 align="center"> Login</h2>

<form  method="POST">
{% csrf_token %}

Username: <br />
<input type="text" placeholder="Enter Username" name="username" />
<br/><br />
Password : <br />
<input type="password" placeholder="Enter Password" name="password" /><br /><br />

<input class="btn btn-primary" type="submit" value="login" />
</form>
</div>
</body>

</html>

accounts/templates/login_mine.html
<!DOCTYPE html>
<html>
<head>
<title>DMS|login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}


input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 12px;
  margin: 18px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
  
}

button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 23px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}


.center {
  margin: auto;
  width: 30%;
  border: 0px solid #73AD21;
  padding: 27px;
    }
.header_bg{
	background: url('../static/images/old_bg.jpg') no-repeat;
	
	/*background-size:cover;*/
	min-height: 110%;
    min-width: 1024px;
	width: 100%;
    height: 110%;
	
  /* Set up proportionate scaling */
  
	
  /* Set up positioning */
  position: fixed;
  top: 0;
  left: 0;
  }
</style>
</head>
<div class="header_bg">
<br><br>
<em><h1 align="center">Prodigy Technosys</h1></em>
<div class="center">



{% block content %}
<br>
<html>
<!--{% block title %}Login{% endblock %} <h2 align="center">Login</h2>-->
{{error}}
  
  <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>

</html>
{% endblock %}
</div>
</div>
<footer class="w3-container w3-center">
    &copy Prodigy Technosys {% now "Y"%}
  </footer>
</html>

accounts/templates/signup1.html
{% extends 'dash.html' %}

{% block content %}
<h2> Create new user</h2>

{{ error }}
<form  method="POST" action="/upload/signup/">
{% csrf_token %}

Username: <br />
<input type="text" name="username" />
<br />
<!--First Name: <br />
<input type="text" name="first_name" />
<br />
Last Name: <br />
<input type="text" name="last_name" />
<br />
Email: <br />
<input type="email" name="email" /><br />-->
{{ form_adduser.as_p }} 
<input class="btn btn-primary" type="submit" value="Submit" />
</form>

{% endblock %}

accounts/templates/user_list.html
<h3> Display total users list: </h3>

  <p><b>Display:</b> <br>{{sp_user_list}}</p>

  
    
    {% for i in sp_user_list %}
      ID: {{i.1}} <br>
      Firstname: {{i.2}} <br><br>
    {% endfor %}